# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-06 04:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkin_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='time',
            options={},
        ),
    ]
