# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-07 19:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='picture',
            field=models.FileField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
