# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-04 18:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkin_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkin_app.Profile'),
        ),
    ]
