# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-06 04:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin_app', '0002_auto_20161106_0408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time',
            name='checkout_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
