# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-06 22:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin_app', '0008_auto_20161106_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='picture',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='child',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='child',
            name='last_name',
            field=models.CharField(max_length=30),
        ),
    ]
