# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-06 22:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkin_app', '0009_auto_20161106_2223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='picture',
        ),
    ]
