# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-06 22:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin_app', '0010_remove_child_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='picture',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
